# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/vocab.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/vocab.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/vocab.proto\x12\x05vocab\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa0\x03\n\rReviewRequest\x12\x19\n\x04\x63\x61rd\x18\x01 \x01(\x0b\x32\x0b.vocab.Card\x12\x0f\n\x07quality\x18\x02 \x01(\x05\x12\x34\n\x0freview_duration\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x37\n\x11request_retention\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x35\n\x10maximum_interval\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\t\n\x01w\x18\x06 \x03(\x01\x12\x32\n\treview_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x1e\n\x16learning_steps_seconds\x18\x08 \x03(\x05\x12 \n\x18relearning_steps_seconds\x18\t \x03(\x05\x12\x1b\n\x0e\x65nable_fuzzing\x18\n \x01(\x08H\x01\x88\x01\x01\x42\x0c\n\n_review_atB\x11\n\x0f_enable_fuzzing\"Q\n\x0eReviewResponse\x12\x19\n\x04\x63\x61rd\x18\x01 \x01(\x0b\x32\x0b.vocab.Card\x12$\n\nreview_log\x18\x02 \x01(\x0b\x32\x10.vocab.ReviewLog\"\xfb\x01\n\x04\x43\x61rd\x12\r\n\x05state\x18\x01 \x01(\x05\x12)\n\x04step\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12.\n\tstability\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12/\n\ndifficulty\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12\'\n\x03\x64ue\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0blast_review\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x86\x01\n\tReviewLog\x12\x0e\n\x06rating\x18\x02 \x01(\x05\x12\x33\n\x0freview_datetime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x0freview_duration\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int32Value2K\n\x0cVocabService\x12;\n\nReviewCard\x12\x14.vocab.ReviewRequest\x1a\x15.vocab.ReviewResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.vocab_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REVIEWREQUEST']._serialized_start=94
  _globals['_REVIEWREQUEST']._serialized_end=510
  _globals['_REVIEWRESPONSE']._serialized_start=512
  _globals['_REVIEWRESPONSE']._serialized_end=593
  _globals['_CARD']._serialized_start=596
  _globals['_CARD']._serialized_end=847
  _globals['_REVIEWLOG']._serialized_start=850
  _globals['_REVIEWLOG']._serialized_end=984
  _globals['_VOCABSERVICE']._serialized_start=986
  _globals['_VOCABSERVICE']._serialized_end=1061
# @@protoc_insertion_point(module_scope)
